/**
 * Build-time Substack fetch.
 *
 * Pulls the RSS feed, extracts each post's title + canonical link, and writes
 * `src/features/home/writing.data.ts`. The editorial home's Writing section
 * reads that generated module and links each title out to the Substack post
 * (no local essay artifacts — blogs live on Substack now).
 *
 * Resilient by design: on any network/parse failure it keeps the last-committed
 * `writing.data.ts` rather than breaking the build. Run via `pnpm substack:fetch`
 * (wired into `prebuild`).
 */
import { writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const SUBSTACK_URL = "https://0x8bu.substack.com";
const FEED_URL = `${SUBSTACK_URL}/feed`;
const MAX_POSTS = 8;
const OUT = join(dirname(fileURLToPath(import.meta.url)), "../src/features/home/writing.data.ts");

interface Post {
  title: string;
  url: string;
}

function decodeEntities(s: string): string {
  return s
    .replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g, "$1")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&quot;/g, '"')
    .trim();
}

function parseFeed(xml: string): Post[] {
  const posts: Post[] = [];
  for (const chunk of xml.split(/<item[\s>]/).slice(1)) {
    const t = chunk.match(/<title>([\s\S]*?)<\/title>/);
    const l = chunk.match(/<link>([\s\S]*?)<\/link>/);
    if (t && l) {
      const title = decodeEntities(t[1]);
      const url = decodeEntities(l[1]);
      if (title && url) posts.push({ title, url });
    }
    if (posts.length >= MAX_POSTS) break;
  }
  return posts;
}

function render(posts: Post[]): string {
  return (
    "// AUTO-GENERATED by scripts/fetch-substack.ts — do not edit by hand.\n" +
    `// Source: ${SUBSTACK_URL} (refreshed at prebuild).\n` +
    "export interface WritingPost {\n  title: string;\n  url: string;\n}\n" +
    `export const SUBSTACK_URL = ${JSON.stringify(SUBSTACK_URL)};\n` +
    `export const WRITING_POSTS: WritingPost[] = ${JSON.stringify(posts, null, 2)};\n`
  );
}

async function main() {
  try {
    const res = await fetch(FEED_URL, { headers: { "user-agent": "8bu.dev build" } });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const posts = parseFeed(await res.text());
    if (!posts.length) throw new Error("no items parsed from feed");
    writeFileSync(OUT, render(posts));
    console.log(`[substack] wrote ${posts.length} post(s) → writing.data.ts`);
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    if (existsSync(OUT)) {
      console.warn(`[substack] fetch failed (${msg}); keeping committed writing.data.ts`);
      return;
    }
    console.warn(`[substack] fetch failed (${msg}) and no existing file; writing empty list`);
    writeFileSync(OUT, render([]));
  }
}

void main();
