import opentype from "opentype.js";

export interface BadgeGeometry {
  glyphsPath: string;
  caretPath: string;
  viewBox: string;
  width: number;
  height: number;
  glyphsMaxX: number;
  caretMinX: number;
}

const TEXT = "8BU";
const CARET = "_";
const FONT_SIZE = 16; // internal vector units; SVG scales freely
const PAD = 4; // internal padding around content (tuned for visual parity)
const PRECISION = 2;

export function vectorizeBadge(fontBuffer: ArrayBuffer): BadgeGeometry {
  const font = opentype.parse(fontBuffer);

  // Pass 1 — measure at baseline 0 to find the content bounding box.
  const caretX = font.getAdvanceWidth(TEXT, FONT_SIZE);
  const g0 = font.getPath(TEXT, 0, 0, FONT_SIZE);
  const c0 = font.getPath(CARET, caretX, 0, FONT_SIZE);
  const gb = g0.getBoundingBox();
  const cb = c0.getBoundingBox();

  const minX = Math.min(gb.x1, cb.x1);
  const minY = Math.min(gb.y1, cb.y1);
  const maxX = Math.max(gb.x2, cb.x2);
  const maxY = Math.max(gb.y2, cb.y2);

  // Pass 2 — translate so content starts at (PAD, PAD).
  const dx = PAD - minX;
  const dy = PAD - minY;
  const glyphs = font.getPath(TEXT, dx, dy, FONT_SIZE);
  const caret = font.getPath(CARET, caretX + dx, dy, FONT_SIZE);

  const width = Math.ceil(maxX - minX + PAD * 2);
  const height = Math.ceil(maxY - minY + PAD * 2);

  return {
    glyphsPath: glyphs.toPathData(PRECISION),
    caretPath: caret.toPathData(PRECISION),
    viewBox: `0 0 ${width} ${height}`,
    width,
    height,
    glyphsMaxX: gb.x2 + dx,
    caretMinX: cb.x1 + dx,
  };
}

// Emit `export const NAME = VALUE;`, wrapping the value onto an indented second
// line when the single-line form would exceed oxfmt's 100-char print width — so
// the generated file matches `oxfmt` output and `format:check` stays green.
function emitConst(name: string, value: string): string {
  const oneLine = `export const ${name} = ${value};`;
  if (oneLine.length <= 100) return oneLine;
  return `export const ${name} =\n  ${value};`;
}

export function renderPathsModule(geo: BadgeGeometry): string {
  return `// GENERATED by pnpm wordmark:build — do not edit by hand.
// Source: scripts/wordmark-fonts/PressStart2P-Regular.ttf via scripts/wordmark-vectorize.ts
${emitConst("WORDMARK_VIEWBOX", JSON.stringify(geo.viewBox))}
${emitConst("WORDMARK_WIDTH", String(geo.width))}
${emitConst("WORDMARK_HEIGHT", String(geo.height))}
${emitConst("WORDMARK_GLYPHS_PATH", JSON.stringify(geo.glyphsPath))}
${emitConst("WORDMARK_CARET_PATH", JSON.stringify(geo.caretPath))}
`;
}

const BADGE_RX = 0; // press theme --radius-sm is 0px — square corners, matches current badge

export function renderStandaloneSvg(geo: BadgeGeometry): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${geo.viewBox}" width="${geo.width}" height="${geo.height}" role="img" aria-label="8BU">
  <title>8BU</title>
  <style>
    .caret { animation: caret-blink 1s steps(2, end) infinite; }
    @keyframes caret-blink { 0%, 50% { opacity: 1; } 50.01%, 100% { opacity: 0; } }
    @media (prefers-reduced-motion: reduce) { .caret { animation: none; } }
  </style>
  <rect x="0" y="0" width="${geo.width}" height="${geo.height}" rx="${BADGE_RX}" fill="#d8200a" />
  <path d="${geo.glyphsPath}" fill="#ffffff" />
  <path class="caret" d="${geo.caretPath}" fill="#ffffff" />
</svg>
`;
}
