import {
  WORDMARK_CARET_PATH,
  WORDMARK_GLYPHS_PATH,
  WORDMARK_HEIGHT,
  WORDMARK_VIEWBOX,
  WORDMARK_WIDTH,
} from "./wordmark-paths";

type WordmarkProps = {
  size?: number;
  sub?: string | null;
};

/**
 * 8BU wordmark — single variant.
 *
 * The badge is an inline SVG of vectorized "Press Start 2P" contours (8BU) plus
 * a blinking "_" caret. Path data is generated by `pnpm wordmark:build` into
 * `wordmark-paths.ts`; no font is fetched for the badge. The badge background
 * uses `var(--coral)` so it follows the active theme; the caret blink + the
 * reduced-motion guard live in `apps/web/src/styles/portfolio.css`
 * (`.wm-blink-caret` / `@keyframes wm-caret-blink`).
 */
export function Wordmark({ size = 14, sub = "Senior Web Developer" }: WordmarkProps) {
  const badgeHeight = size; // badge ≈ wordmark line height; scales crisply
  const badgeWidth = (WORDMARK_WIDTH / WORDMARK_HEIGHT) * badgeHeight;
  return (
    <span className="wm" style={{ fontSize: size }}>
      <span className="wm-mark wm-mark-blockcursor" style={{ display: "inline-flex" }}>
        <svg
          className="wm-badge-svg"
          viewBox={WORDMARK_VIEWBOX}
          width={badgeWidth}
          height={badgeHeight}
          role="img"
          aria-label="8BU"
        >
          <rect
            x="0"
            y="0"
            width={WORDMARK_WIDTH}
            height={WORDMARK_HEIGHT}
            rx="0"
            fill="var(--coral)"
          />
          <path d={WORDMARK_GLYPHS_PATH} fill="#ffffff" aria-hidden="true" />
          <path
            className="wm-blink-caret"
            d={WORDMARK_CARET_PATH}
            fill="#ffffff"
            aria-hidden="true"
          />
        </svg>
      </span>
      <span className="wm-text" style={{ fontSize: size }}>
        Long NGUYỄN
      </span>
      {sub ? <span className="wm-sub">- {sub}</span> : null}
    </span>
  );
}
