// AUTO-GENERATED by scripts/fetch-substack.ts — do not edit by hand.
// Source: https://0x8bu.substack.com (refreshed at prebuild).
export interface WritingPost {
  title: string;
  url: string;
}
export const SUBSTACK_URL = "https://0x8bu.substack.com";
export const WRITING_POSTS: WritingPost[] = [
  {
    "title": "The R in RAG, Hold the G",
    "url": "https://0x8bu.substack.com/p/the-r-in-rag-hold-the-g"
  }
];
