import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import { renderPathsModule, renderStandaloneSvg, vectorizeBadge } from "../wordmark-vectorize";

const __dirname = dirname(fileURLToPath(import.meta.url));
const FONT = join(__dirname, "..", "wordmark-fonts", "PressStart2P-Regular.ttf");

function fontArrayBuffer(): ArrayBuffer {
  const buf = readFileSync(FONT);
  return buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength) as ArrayBuffer;
}

describe("vectorizeBadge", () => {
  it("returns non-empty path data for glyphs and caret", () => {
    const geo = vectorizeBadge(fontArrayBuffer());
    expect(geo.glyphsPath.length).toBeGreaterThan(10);
    expect(geo.caretPath.length).toBeGreaterThan(5);
    expect(geo.glyphsPath.startsWith("M")).toBe(true);
  });

  it("produces a positive viewBox sized to content + padding", () => {
    const geo = vectorizeBadge(fontArrayBuffer());
    expect(geo.width).toBeGreaterThan(0);
    expect(geo.height).toBeGreaterThan(0);
    expect(geo.viewBox).toBe(`0 0 ${geo.width} ${geo.height}`);
  });

  it("places the caret to the right of the 8BU glyphs", () => {
    const geo = vectorizeBadge(fontArrayBuffer());
    // caret path's leftmost x should sit at/after the glyphs' max x extent
    expect(geo.caretMinX).toBeGreaterThan(geo.glyphsMaxX - 1);
  });
});

describe("renderPathsModule", () => {
  it("emits a generated-header TS module exporting the consts", () => {
    const geo = vectorizeBadge(fontArrayBuffer());
    const out = renderPathsModule(geo);
    expect(out).toContain("GENERATED by pnpm wordmark:build");
    expect(out).toContain("export const WORDMARK_VIEWBOX");
    expect(out).toContain("export const WORDMARK_GLYPHS_PATH");
    expect(out).toContain("export const WORDMARK_CARET_PATH");
    expect(out).toContain(geo.glyphsPath);
  });
});

describe("renderStandaloneSvg", () => {
  it("emits a self-contained svg with baked coral, title, blink style", () => {
    const geo = vectorizeBadge(fontArrayBuffer());
    const svg = renderStandaloneSvg(geo);
    expect(svg.startsWith("<svg")).toBe(true);
    expect(svg).toContain('xmlns="http://www.w3.org/2000/svg"');
    expect(svg).toContain("<title>8BU</title>");
    expect(svg).toContain("#d8200a");
    expect(svg).toContain("@keyframes");
    expect(svg).toContain("steps(2, end)");
    expect(svg).toContain("prefers-reduced-motion");
    expect(svg).toContain(geo.caretPath);
    expect(svg.trimEnd().endsWith("</svg>")).toBe(true);
  });
});
